version: "3.9"

services:
  strapi:
    build: .
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    ports:
      - "1337:1337"
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: strapi_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
